### ISSUE TITLE
Support Svelte's $$Generic type

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/svelte-eslint-parser#306]
I'm not sure if this is a bug or a feature but I think `svelte-eslint-parser` doesn't support Svelte's `$$Generic` type to type component properties.

![image](https://user-images.githubusercontent.com/209056/227035301-64cf2b98-5e3f-42a6-b4f8-bb84e034e309.png)

Relevant information is probably this: https://github.com/sveltejs/eslint-plugin-svelte3/issues/127

**Comment by ota-meshi** [comment]
Thank you for posting issue.

The RFC about `$$Generic` don't seem to have been merged yet.
sveltejs/rfcs#38
I don't want to fully support it yet to avoid a lot of breaking changes.
If you want to support it, we can add it as an experimental feature.

--

Related to https://github.com/ota-meshi/eslint-plugin-svelte/issues/390

**Comment by ptrxyz** [comment]
I see, so it is on the radar somehow but needs some deeper digging. Thanks a bunch.
Feel free to close this issue or keep it open to keep track of `$$Generic`.

For anyone stumbling across this: for now I simply workaround by defining `$$Generic` globally in my eslintrc:

```js
...
        env: {
                ...
        }, 
        globals: {
		$$Generic: 'readonly'
	},
...
```

**Comment by dummdidumm** [comment]
@ota-meshi I'm exploring an alternative syntax for this currently, which would look like this:

```svelte
<script lang="ts" generics="T, X extends string">
  export let items: T[];
  export let key: X;
</script>
```

From an implementation-perspective, how hard would it be for `svelte-eslint-parser` to support this syntax?

(I'm not saying it's decided that we switch to this syntax yet, but I want to have as much feedback as possible before making the decision)

**Comment by ota-meshi** [comment]
Thank you for letting me know.
Vue team is also exploring `generic` attribute, so I'm looking into how to support it with the `vue-eslint-parser`.
(I'm the maintainer of eslint-plugin-vue and vue-eslint-parser.)

The current idea is to insert virtual code like this:

```ts
type T = unknown;
type X = string;
```

In TypeScript, this might generate the wrong type like the following example code, but I anticipate no problem within the scope of the checks used in typescript-eslint.

```svelte
<script lang="ts" generics="T extends string | number">
  let val: T = 42 // It's a type error in TypeScript.
</script>
```

↓ Virtual code

```ts
type T = string | number
let val: T = 42 // It's not an error. Also, `val` is inferred to be of type number.
```

**Comment by wvhulle** [comment]
> @ota-meshi I'm exploring an alternative syntax for this currently, which would look like this:
> 
> ```svelte
> <script lang="ts" generics="T, X extends string">
>   export let items: T[];
>   export let key: X;
> </script>
> ```
> 
> From an implementation-perspective, how hard would it be for `svelte-eslint-parser` to support this syntax?
> 
> (I'm not saying it's decided that we switch to this syntax yet, but I want to have as much feedback as possible before making the decision)

It would be nice to keep the $$Generic in inside the script. If you have a lot of generics you can't just write them on one line. 

And can you keep the types interactive and highlighted as a generics property?

**Comment by connerdassen** [comment]
Why is this not supported? 
The now obsolete eslint-plugin-svelte3 had this added a year and 8 months ago. 
Defining $$Generic globally in eslintrc gets rid of the undefined error but causes problems later on because it is assigned an "any" type, leading to no-unsafe-member-access errors later on when trying to use the type defined by $$Generic

**Comment by dummdidumm** [comment]
It's not supported yet because it's still experimental, which is a valid choice.

**Comment by probablykasper** [comment]
Would love to update to Svelte 4, but the deprecated `eslint-plugin-svelte3` doesn't support it. Was I unknowingly using an experimental feature, or is it just not supported anymore? Are there any plans for when to address it?

**Comment by theodorejb** [comment]
@probablykasper Switch to `eslint-plugin-svelte`.

**Comment by probablykasper** [comment]
@theodorejb I would love to, but it sounds like `$$Generic` is unsupported, without any workaround

**Comment by jjnp** [comment]
> 

Would you be open to a PR to add support for the feature, even if it's still just an RFC? If you are focused on other tasks, which I of course understand, I'd try to look into what I can do to help the feature along. We're using generics in multiple production apps and having this break with the upgrade to svelte-4 is a step back for our project setup...

**Comment by ota-meshi** [comment]
I think we can add support for `Generics` to `svelte-eslint-parser` as an experimental feature. Please consider submitting a PR. However, please allow it to be opted in using something like `parserOptions`.
However, `$$Generic` seems to have been discarded from the RFC, so we won't be adding support for it in the future.

**Comment by niemyjski** [comment]
It's pretty bad dev experience when the official docs say to use these features but then linting fails out of the box when using these features...

**Comment by jjnp** [comment]
> It's pretty bad dev experience when the official docs say to use these features but then linting fails out of the box when using these features...

Yes... I'm looking into writing a PR to add support for it, but I haven't gotten around to it yet since I'm not yet familiar with developing eslint-plugin related things^^

**Comment by AlbertMarashi** [comment]
Yeah also ran into this issue. I thought I was doing something wrong but apparently not

**Comment by AlbertMarashi** [comment]
Temporary workaround for those people who's `T` is unknown/generic
```ts
// TODO: REMOVE WHEN https://github.com/sveltejs/svelte-eslint-parser/issues/306 IS FIXED
// eslint-disable-next-line no-undef, @typescript-eslint/no-explicit-any
type X = T | any

export let options = X[]
```
This will get the errors to disappear

**Comment by AlbertMarashi** [comment]
@Rich-Harris  will this be fixed in Svelte 5?

**Comment by dummdidumm** [comment]
`$$Generic` is deprecated in favor of the `generics` attribute, which should be supported in this parser at some point. For more info see https://github.com/sveltejs/svelte-eslint-parser/issues/306#issuecomment-1486604484

**Comment by AlbertMarashi** [comment]
I see. Is there any issues that need resolving that perhaps I could help work on?

**Comment by dummdidumm** [comment]
I'll defer to @ota-meshi and @baseballyama for this question

**Comment by ota-meshi** [comment]
I think if someone works on this implementation, it can be added as an experimental feature.
https://github.com/sveltejs/svelte-eslint-parser/issues/306#issuecomment-1704455018
