### ISSUE TITLE
Update the url in description

### ISSUE THREAD

**Issue by so1ve** [sveltejs/svelte-eslint-parser#320]
The url points to old url (ota-meshi), please update it

**Comment by ota-meshi** [comment]
I'm unable to edit it because the repository has been transferred.

@Rich-Harris @Conduitry @baseballyama 
Could you please change the settings of [svelte-eslint-parser] and [eslint-plugin-svelte] so that I can edit it?

[svelte-eslint-parser]: https://github.com/sveltejs/svelte-eslint-parser
[eslint-plugin-svelte]: https://github.com/sveltejs/eslint-plugin-svelte

**Comment by Conduitry** [comment]
Hello @ota-meshi! Sorry about the delay on this. I'm not sure what those permissions would be, exactly, other than complete admin control over the repos. I still find GitHub's permissions model really confusing. I've gone ahead and edited the description of each repo to point to sveltejs.github.io though. Let me know if there's something else you needed.

**Comment by baseballyama** [comment]
Thank you @Conduitry!
Maybe if we can access to `setting` page, it's very helpful!
(e.g. Adding GitHub actions secrets)

I described how to add permission below.

<img width="871" alt="Screenshot 2023-04-23 at 23 48 44" src="https://user-images.githubusercontent.com/19153718/233846822-73464142-4f75-4775-b45a-58449619762b.png">

### To add the permission, you can go to `Collaborators and teams` from setting tab,

<img width="343" alt="Screenshot 2023-04-23 at 23 54 38" src="https://user-images.githubusercontent.com/19153718/233847098-4071acef-5771-46a5-93b9-76ec7e5ff9d2.png">

### then press `Add people`,

<img width="786" alt="Screenshot 2023-04-23 at 23 53 50" src="https://user-images.githubusercontent.com/19153718/233847043-4f7552cd-4f00-4938-899d-5585c3c60d4e.png">

### type `oth-meshi` and select `ota-meshi`,

<img width="617" alt="image" src="https://user-images.githubusercontent.com/19153718/233847176-75d9a969-ccb5-4d34-bc5c-63f12800be10.png">

### Select `admin` and click `Add xxx to this repository` button.

<img width="641" alt="Screenshot 2023-04-23 at 23 58 40" src="https://user-images.githubusercontent.com/19153718/233847278-b617e29b-4533-481a-aa1e-59cb4be0724c.png">

**Comment by Conduitry** [comment]
I'd like to try to limit admin access just as a general rule, if possible. So @baseballyama @ota-meshi I've given you both the 'maintain' role on both repos. I'm not sure which settings that gives you access to, exactly. I'd like to see whether that's going to be enough for day-to-day activities on the project. I'm hoping things requiring admin access will only come up occasionally, and that you can just ping me or another org admin to do those manually.

**Comment by so1ve** [comment]
Should I close this issue? The URL is updated.

**Comment by baseballyama** [comment]
@Conduitry Thank you and agree. Let's follow principle of least privilege, and again I will ask you if I need some more permission.

**Comment by baseballyama** [comment]
> Should I close this issue? The URL is updated.

Yes. Thank you!

**Comment by ota-meshi** [comment]
@Conduitry Thank you! Now I have access to edit "About" and some of the "Settings" of this repository.

This is out of the topic of this issue, but could you enable Changesets and Renovate apps for the `svelte-eslint-parser` and `eslint-plugin-svelte` repositories? 
It seems that they can only be set by authorized members of the organization.
(I previously requested it from the app settings, but I don't know if it notified you. 😅)
