### ISSUE TITLE
version is not found when using bun package manager

### ISSUE THREAD

**Issue by ksmsk** [sveltejs/svelte-eslint-parser#482]
i'm trying svelte 5 right now i'm quite enjoying it so far. i'd like to give it a go with bun on my side hustle but i'm getting `error: No version matching ">=0.34.0-next.9 <1.0.0" found for specifier "svelte-eslint-parser" (but package exists)` error message when i try to use `bun install`. since it's pre release version and this things can happen, i just want you to know it.

**Comment by ota-meshi** [comment]
I'm not sure. The target version exists. I think it's a bug in Bun.
https://www.npmjs.com/package/svelte-eslint-parser/v/0.34.0-next.9

**Comment by ksmsk** [comment]
for people who might stuck in the future: updating bun to v1.0.29 has fixed the issue.
