### ISSUE TITLE
[question] what about @stylistic/eslint-plugin

### ISSUE THREAD

**Issue by rallets** [sveltejs/svelte-eslint-parser#554]
Hi, I just noticed that eslint had deprecated the stylistic rules from 8.53.0. I have an existing project configured using a previous version, and now I'm trying to migrate to the new suggested package `@stylistic/eslint-plugin`.
As few changes are needed around the config changes, I'm wondering how the config for svelte and this package could be affected. 
Any idea?
Thank you

**Comment by ota-meshi** [comment]
I think if you migrate to `@stylistic/eslint-plugin` it will work.
This package should not be affected.
